server:
  servlet:
    context-path: /api

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/eventlistener
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  main:
    lazy-initialization: false

